---
- name: Add apt repo key
  become: true
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  register: add_repo_key
  ignore_errors: true

- name: Add docker repo
  become: true
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      update_cache: yes
      state: present

- name: Install docker
  become: true
  apt:
      name: "docker-ce={{ docker_version }}*"

- name: Add ubuntu user to docker group
  become: true
  user: name=ubuntu groups=docker append=yes

- name: Creates New Docker HTTP Proxy folder
  become: true
  file: 
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: "u=rwx,g=wx,o=rwx"

- name: Configure HTTP Proxy for Docker
  become: true  
  copy:
    src: http-proxy.conf
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    owner: root
    group: root
    mode: 0777

- name: Configure HTTPS Proxy for Docker
  become: true  
  copy:
    src: https-proxy.conf
    dest: /etc/systemd/system/docker.service.d/https-proxy.conf
    owner: root
    group: root
    mode: 0777

- name: Docker-restart-service
  become: true
  command: sudo systemctl restart docker

- name: Docker-restart-service
  become: true
  command: sudo systemctl daemon-reload

- name: sleep for 180 seconds before continue
  wait_for: timeout=180
  delegate_to: localhost

#- name: Docker-restart-service
#  become: true
#  service:
#    name: 'docker'
#    state: 'restarted'
#    enabled: 'yes'

 

