heat_template_version: 2013-05-23

description:  OOM Template 

parameters:
  key_name:
    type: string
    default: ONAP
    description: You own existing key pair to use for the instance
  flavor:
    type: string
    description: Instance type for OOM
    default: ONAP_FSB
  image:
    type: string
    default: ubuntu_xenial
    description: ID or name of the image to use for the instance
  user:
    type: string
    description: Default user
    default: ubuntu1604
  net1:
    type: string
    description: (existing) network for the server to be created
    default: ONAP_ProvNet_1
    constraints:
      - custom_constraint: neutron.network
  AnsibleRepository:
    type: string
    label: Ansible Repository
    description: Ansible Repository for playbooks and roles.
  AnsiblePlaybook:
    type: string
    label: Ansible Playbook
    description: Ansible Playbook Startup.
  OOMTemplate:
    type: string
    label: OOM Template to deploy
    description: OOM Size to deploy.  
  
resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      name: OOM
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      config_drive: 'True'
#      block_device_mapping: [{volume_id: { get_param: fsb2_cinder_vol }, device_name: vda}]
      networks:
        - network: {get_param: net1}
      user_data:
        str_replace:
          params:
            __AnsibleRepository__: { get_param: AnsibleRepository }
            __AnsiblePlaybook__: { get_param: AnsiblePlaybook }
            __OOMTemplate__: { get_param: OOMTemplate }
          template: |
            #!/bin/bash -ex
               http_proxy=http://10.7.0.140:8080/
               https_proxy=http://10.7.0.140:8080/
              #no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
              HTTP_PROXY=http://10.7.0.140:8080/
              HTTPS_PROXY=http://10.7.0.140:8080/
              #NO_PROXY="localhost,127.0.0.1,localaddress,.localdomain.com"
            # install dependencies
            sudo apt-add-repository ppa:ansible/ansible -y 
            sudo apt-get update -y
            sudo apt-get install -y ansible git
            # Configure Ansible
            echo "localhost ansible_connection=local" > /etc/ansible/hosts
            echo "log_path = /var/log/ansible.log" >> /etc/ansible/ansible.cfg
            # Launch Installer
            #sudo ansible-pull -U ", __AnsibleRepository__," ","-e"," ","config=",__OOMTemplate__," ",__AnsiblePlaybook__," ","-vvvv"," 
              

output:
  instance_name:
    description: Get the instance's name
    value: { get_attr: [ my_instance, name ] }
  instance_ip:
    description: IP address of the instance
    value: { get_attr: [my_instance, first_address] }