---
- hosts: localhost
  gather_facts: no
  pre_tasks:
    - name: install python
      raw: sudo apt-get install -y python-minimal
  roles:
      - common 
      - docker
      - volumes
      - k8s
      - helm
      - tiller
